version: '2'
services:
  postgres:
    image: 'postgres:9.5'
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'solarpass'
    ports:
      - '5432:5432'
    volumes:
      - 'postgres:/var/lib/postgresql/data'
  app:
    image: clevertechru/solar
    environment:
      RAILS_ENV: development
    depends_on:
      - postgres
    build: .
    container_name: docker-solar
    command: bash -c "rake db:create && rake db:migrate && rails server -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    links:
      - postgres
volumes:
  postgres: