# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a5aa673af973d707e6395b109021557fca837b9a4097a54f062414e567422be8de11d95b92b8d4632041879029c8901e2cf284f2ac0a62f1428f5726f3be6815

test:
  secret_key_base: fec2d925e5e665548a481ab6dac9eaa7b826cc7024909407319dca92a42cb28b740b907cfa76c26c0d4229a5cdc25c5af4da2f2dc8617caed1bac00ac314df07

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
